// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhrpctazywotzcpazyrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocnBjdGF6eXdvdHpjcGF6eXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzU5NzksImV4cCI6MjA3MDE1MTk3OX0.pR5JJYdLtxqmN8KiRO5pis46nR_0hLfeet-FqPZjgCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});